language: go

go:
  - "1.10"

services:
  - docker

deploy:
  provider: script
  skip_cleanup: true
  script: 
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
